/* 21HTTT1 - Nhóm 3
 * 21127004 - Trần Nguyễn An Phong
 * 21127135 - Diệp Hữu Phúc
 * 21127149 - Huỳnh Minh Quang
 * 21127296 - Đặng Hà Huy
 */
USE [Nhom3_QLNhaKhoa]
GO

--TAO KHACH HANG
CREATE OR ALTER PROC USP_KHACHHANG_INS
    @HOTEN NVARCHAR(25),
    @NGAYSINH DATE,
    @DIACHI NVARCHAR(50),
    @SODT VARCHAR(11),
    @MATKHAU VARCHAR(20),
    @MAKHACHHANG VARCHAR(5) OUTPUT
AS BEGIN TRAN
    SELECT @MAKHACHHANG = MAKHACHHANG FROM KHACHHANG
    WHERE MAKHACHHANG = (SELECT MAX(MAKHACHHANG) FROM KHACHHANG)

    IF (@MAKHACHHANG IS NULL) SET @MAKHACHHANG = 'KH001'
    ELSE BEGIN
        SET @MAKHACHHANG = CAST(RIGHT(@MAKHACHHANG, 3) AS INT) + 1
        SET @MAKHACHHANG = 'KH' + RIGHT('000'
            + CAST(@MAKHACHHANG AS VARCHAR(3)), 3)
    END

    INSERT INTO KHACHHANG
    VALUES (@MAKHACHHANG, @HOTEN, @NGAYSINH, @DIACHI, @SODT, @MATKHAU)
COMMIT TRAN
GO

--CHINH SUA THONG TIN KHACH HANG
CREATE OR ALTER PROC USP_KHACHHANG_UPD
    @MAKHACHHANG VARCHAR(5),
    @NGAYSINH DATE,
    @DIACHI NVARCHAR(50),
    @SODT VARCHAR(11),
    @MATKHAU VARCHAR(20)
AS BEGIN TRAN
    IF NOT EXISTS (SELECT * FROM KHACHHANG WHERE MAKHACHHANG = @MAKHACHHANG) BEGIN
        RAISERROR('KHACH HANG KHONG TON TAI', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF (@NGAYSINH IS NOT NULL) BEGIN
        UPDATE KHACHHANG
        SET NGAYSINH = @NGAYSINH
        WHERE MAKHACHHANG = @MAKHACHHANG
    END

    IF (@DIACHI IS NOT NULL) BEGIN
        UPDATE KHACHHANG
        SET DIACHI = @DIACHI
        WHERE MAKHACHANG = @MAKHACHANG
    END

    IF (@SODT IS NOT NULL) BEGIN
        UPDATE KHACHHANG 
        SET SODT = @SODT
        WHERE MAKHACHHANG = @MAKHACHANG
    END

    IF (@MATKHAU IS NOT NULL) BEGIN
        UPDATE KHACHHANG 
        SET MATKHAU = @MATKHAU
        WHERE MAKHACHHANG = @MAKHACHHANG
    END

COMMIT TRAN
GO
