/* 21HTTT1 - Nhóm 3
 * 21127004 - Trần Nguyễn An Phong
 * 21127135 - Diệp Hữu Phúc
 * 21127149 - Huỳnh Minh Quang
 * 21127296 - Đặng Hà Huy
 */
USE [Nhom3_QLNhaKhoa]
GO

CREATE OR ALTER PROC USP_KHACHHANG_INS
    @HOTEN NVARCHAR(25),
    @NGAYSINH DATE,
    @DIACHI NVARCHAR(50),
    @SODT VARCHAR(11),
    @MATKHAU VARCHAR(20),
    @MAKHACHHANG VARCHAR(5) OUTPUT
AS BEGIN TRAN
    SELECT @MAKHACHHANG = MAKHACHHANG FROM KHACHHANG
    WHERE MAKHACHHANG = (SELECT MAX(MAKHACHHANG) FROM KHACHHANG)

    IF (@MAKHACHHANG IS NULL) SET @MAKHACHHANG = 'KH001'
    ELSE BEGIN
        SET @MAKHACHHANG = CAST(RIGHT(@MAKHACHHANG, 3) AS INT) + 1
        SET @MAKHACHHANG = 'KH' + RIGHT('000'
            + CAST(@MAKHACHHANG AS VARCHAR(3)), 3)
    END

    INSERT INTO KHACHHANG
    VALUES (@MAKHACHHANG, @HOTEN, @NGAYSINH, @DIACHI, @SODT, @MATKHAU)
COMMIT TRAN
GO