/* 21HTTT1 - Nhóm 3
 * 21127004 - Trần Nguyễn An Phong
 * 21127135 - Diệp Hữu Phúc
 * 21127149 - Huỳnh Minh Quang
 * 21127296 - Đặng Hà Huy
 */
USE [Nhom3_QLNhaKhoa]
GO

CREATE OR ALTER PROC USP_LICHHEN_INS
    @NGAY DATE,
    @GIO INT,
    @MAKHACHHANG VARCHAR(5),
    @MANHASI VARCHAR(5),
    @MANVDATLICH VARCHAR(5) = NULL
AS BEGIN TRAN
    IF @GIO < 480 OR @GIO > 1020 BEGIN
        RAISERROR('GIO HAS TO BE BETWEEN 480 AND 1020 (8AM - 5PM)', 16, 1)
        ROLLBACK TRAN
        RETURN -2
    END

    IF NOT EXISTS (SELECT * FROM KHACHHANG
        WHERE MAKHACHHANG = @MAKHACHHANG) BEGIN
        RAISERROR('INVALID MAKHACHHANG', 16, 1)
        ROLLBACK TRAN
        RETURN -3
    END

    IF NOT EXISTS (SELECT * FROM NHANVIEN
        WHERE MANHANVIEN = @MANHASI) BEGIN
        RAISERROR('INVALID MANHASI', 16, 1)
        ROLLBACK TRAN
        RETURN -4
    END

    IF @MANVDATLICH IS NOT NULL AND NOT EXISTS
        (SELECT * FROM NHANVIEN WHERE MANHANVIEN = @MANVDATLICH) BEGIN
        RAISERROR('INVALID MANVDATLICH', 16, 1)
        ROLLBACK TRAN
        RETURN -5
    END

    DECLARE @MALICHHEN VARCHAR(5)
    SELECT @MALICHHEN = MALICHHEN FROM LICHHEN
    WHERE MALICHHEN = (SELECT MAX(MALICHHEN) FROM LICHHEN)

    IF (@MALICHHEN IS NULL) SET @MALICHHEN = 'LH001'
    ELSE BEGIN
        SET @MALICHHEN = CAST(RIGHT(@MALICHHEN, 3) AS INT) + 1
        SET @MALICHHEN = 'LH' + RIGHT('000'
            + CAST(@MALICHHEN AS VARCHAR(3)), 3)
    END

    INSERT INTO LICHHEN
    VALUES (@MALICHHEN, @NGAY, @GIO, @MAKHACHHANG, @MANHASI, @MANVDATLICH)
COMMIT TRAN
GO