/* 21HTTT1 - Nhóm 3
 * 21127004 - Trần Nguyễn An Phong
 * 21127135 - Diệp Hữu Phúc
 * 21127149 - Huỳnh Minh Quang
 * 21127296 - Đặng Hà Huy
 */
USE [Nhom3_QLNhaKhoa]
GO

CREATE OR ALTER PROC USP_LICHHEN_INS
    @NGAY DATE,
    @GIO INT,
    @MAKHACHHANG VARCHAR(5),
    @MANHASI VARCHAR(5),
    @MANVDATLICH VARCHAR(5) = NULL,
    @MALICHHEN VARCHAR(5) = NULL OUTPUT
AS BEGIN TRAN
    IF @GIO < 480 OR @GIO > 1020 BEGIN
        RAISERROR('GIO HAS TO BE BETWEEN 480 AND 1020 (8AM - 5PM)', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF NOT EXISTS (SELECT * FROM KHACHHANG
        WHERE MAKHACHHANG = @MAKHACHHANG) BEGIN
        RAISERROR('INVALID MAKHACHHANG', 16, 1)
        ROLLBACK TRAN
        RETURN -2
    END

    IF NOT EXISTS (SELECT * FROM NHANVIEN
        WHERE MANHANVIEN = @MANHASI) BEGIN
        RAISERROR('INVALID MANHASI', 16, 1)
        ROLLBACK TRAN
        RETURN -3
    END

    IF @MANVDATLICH IS NOT NULL AND NOT EXISTS
        (SELECT * FROM NHANVIEN WHERE MANHANVIEN = @MANVDATLICH) BEGIN
        RAISERROR('INVALID MANVDATLICH', 16, 1)
        ROLLBACK TRAN
        RETURN -4
    END

    SELECT @MALICHHEN = MALICHHEN FROM LICHHEN
    WHERE MALICHHEN = (SELECT MAX(MALICHHEN) FROM LICHHEN)

    SET @MALICHHEN = dbo.F_MAKE_ID('LH', @MALICHHEN)

    INSERT INTO LICHHEN
    VALUES (@MALICHHEN, @NGAY, @GIO, @MAKHACHHANG, @MANHASI, @MANVDATLICH)
COMMIT TRAN
GO

--SUA MOT LICH HEN CA NHAN CUA NHA SI
CREATE OR ALTER PROC USP_LICHHEN_UPD 
    @MALICHHEN VARCHAR(5),
    @NGUOIUPDATE VARCHAR(5),
    @NGAY DATE,
    @GIO INT,
    @MAKHACHHANG VARCHAR(5)
AS BEGIN TRAN
    IF NOT EXISTS (SELECT * FROM LICHHEN WHERE MALICHHEN = @MALICHHEN) BEGIN
        RAISERROR('LICH HEN KHONG TON TAI', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    DECLARE @MANHASI VARCHAR(5)
    DECLARE @MANVDATLICH VARCHAR(5)
    SELECT @MANHASI = MANHASI FROM LICHHEN WHERE MALICHHEN = @MALICHHEN
    SELECT @MANVDATLICH = MANVDATLICH FROM LICHHEN WHERE MALICHHEN = @MALICHHEN
    
    IF (@MANHASI != @MANVDATLICH) BEGIN
        RAISERROR('DAY KHONG PHAI LICH CA NHAN DO NHA SI TU THEN', 16, 1)
        ROLLBACK TRAN
        RETURN -2
    END

    IF (@NGUOIUPDATE != @MANHASI) BEGIN
        RAISERROR('BAN KHONG CO QUYEN SUA LICH CA NHAN CUA NHA SI NAY', 16, 1)
        ROLLBACK TRAN
        RETURN -3
    END

    IF (@GIO IS NOT NULL AND (@GIO < 480 OR @GIO > 1020)) BEGIN
        RAISERROR('GIO HAS TO BE BETWEEN 480 AND 1020 (8AM - 5PM)', 16, 1)
        ROLLBACK TRAN
        RETURN -4
    END

    IF (@MAKHACHANG IS NOT NULL AND (NOT EXISTS(SELECT * FROM KHACHHANG WHERE MAKHACHANG = @MAKHACHHANG)))
    BEGIN
        RAISERROR('THONG TIN UPDATE KHACH HANG KHONG HOP LE')
        ROLLBACK TRAN
        RETURN -5
    END


    IF (@NGAY IS NOT NULL) BEGIN
        UPDATE LICHHEN
        SET NGAY = @NGAY
        WHERE MALICHHEN = @MALICHHEN
    END

    IF (@GIO IS NOT NULL) BEGIN
        UPDATE LICHHEN
        SET GIO = @GIO
        WHERE MALICHHEN = @MALICHHEN
    END

    IF (@MAKHACHANG IS NOT NULL) BEGIN
        UPDATE LICHHEN
        SET MAKHACHANG = @MAKHACHHANG
        WHERE MALICHHEN = @MALICHHEN
    END

COMMIT TRAN
GO
