/* 21HTTT1 - Nhóm 3
 * 21127004 - Trần Nguyễn An Phong
 * 21127135 - Diệp Hữu Phúc
 * 21127149 - Huỳnh Minh Quang
 * 21127296 - Đặng Hà Huy
 */
USE [Nhom3_QLNhaKhoa]
GO

CREATE OR ALTER PROC USP_MISC_LOGIN
    @MAUSER VARCHAR(5),
    @MATKHAU VARCHAR(20),
    @LOAIUSER INT OUTPUT -- -1: KHACHHANG, 0: NHANVIEN,
                        -- 1: NHASI, 2: QUANTRIVIEN
AS
    IF EXISTS (SELECT * FROM KHACHHANG
        WHERE MAKHACHHANG = @MAUSER AND MATKHAU = @MATKHAU) BEGIN
        SET @LOAIUSER = -1
        RETURN 0
    END

    SELECT @LOAIUSER = LOAINHANVIEN FROM NHANVIEN
        WHERE MANHANVIEN = @MAUSER AND MATKHAU = @MATKHAU
    
    IF (@LOAIUSER IS NULL) BEGIN
        RAISERROR('INVALID MAUSER OR MATKHAU', 16, 1)
        RETURN -1
    END

    RETURN 0
GO