/* 21HTTT1 - Nhóm 3
 * 21127004 - Trần Nguyễn An Phong
 * 21127135 - Diệp Hữu Phúc
 * 21127149 - Huỳnh Minh Quang
 * 21127296 - Đặng Hà Huy
 */
USE [Nhom3_QLNhaKhoa]
GO

CREATE OR ALTER PROC USP_NHANVIEN_INS
    @HOTEN NVARCHAR(25),
    @DIACHI NVARCHAR(50),
    @SODT VARCHAR(11),
    @LOAINHANVIEN INT,
    @MATKHAU VARCHAR(20)
AS BEGIN TRAN
    DECLARE @TYPE CHAR(2), @MANHANVIEN VARCHAR(5)
    IF (@LOAINHANVIEN = 0) SET @TYPE = 'NV'
    IF (@LOAINHANVIEN = 1) SET @TYPE = 'NS'
    IF (@LOAINHANVIEN = 2) SET @TYPE = 'AD'
    
    SELECT @MANHANVIEN = MANHANVIEN FROM NHANVIEN
    WHERE MANHANVIEN = (SELECT MAX(MANHANVIEN) FROM NHANVIEN
        WHERE MANHANVIEN LIKE @TYPE + '%')

    IF (@MANHANVIEN IS NULL) SET @MANHANVIEN = @TYPE + '001'
    ELSE BEGIN
        SET @MANHANVIEN = CAST(RIGHT(@MANHANVIEN, 3) AS INT) + 1
        SET @MANHANVIEN = @TYPE + RIGHT('000'
            + CAST(@MANHANVIEN AS VARCHAR(3)), 3)
    END

    INSERT INTO NHANVIEN
    VALUES (@MANHANVIEN, @HOTEN, @DIACHI, @SODT, @LOAINHANVIEN, @MATKHAU)
COMMIT TRAN
GO