/* 21HTTT1 - Nhóm 3
 * 21127004 - Trần Nguyễn An Phong
 * 21127135 - Diệp Hữu Phúc
 * 21127149 - Huỳnh Minh Quang
 * 21127296 - Đặng Hà Huy
 */
USE [Nhom3_QLNhaKhoa]
GO

CREATE OR ALTER PROC USP_NHANVIEN_INS
    @HOTEN NVARCHAR(25),
    @DIACHI NVARCHAR(50),
    @SODT VARCHAR(11),
    @LOAINHANVIEN INT,
    @MATKHAU VARCHAR(20),
    @MANHANVIEN VARCHAR(5) = NULL OUTPUT
AS BEGIN TRAN
    DECLARE @TYPE CHAR(2)
    IF (@LOAINHANVIEN = 0) SET @TYPE = 'NV'
    ELSE IF (@LOAINHANVIEN = 1) SET @TYPE = 'NS'
    ELSE IF (@LOAINHANVIEN = 2) SET @TYPE = 'AD'
    ELSE BEGIN
        RAISERROR('INVALID LOAINHANVIEN', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END
    
    SELECT @MANHANVIEN = MANHANVIEN FROM NHANVIEN
    WHERE MANHANVIEN = (SELECT MAX(MANHANVIEN) FROM NHANVIEN
        WHERE MANHANVIEN LIKE @TYPE + '%')

    SET @MANHANVIEN = dbo.F_MAKE_ID(@TYPE, @MANHANVIEN)

    INSERT INTO NHANVIEN
    VALUES (@MANHANVIEN, @HOTEN, @DIACHI, @SODT, @LOAINHANVIEN, @MATKHAU)
COMMIT TRAN
RETURN 0
GO