/* 21HTTT1 - Nhóm 3
 * 21127004 - Trần Nguyễn An Phong
 * 21127135 - Diệp Hữu Phúc
 * 21127149 - Huỳnh Minh Quang
 * 21127296 - Đặng Hà Huy
 */
USE [Nhom3_QLNhaKhoa]
GO

/* Thêm, xóa, sửa TOATHUOC
 */
CREATE OR ALTER PROC USP_TOATHUOC_INS
    @MAGIAYKHAMBENH VARCHAR(5),
    @MATHUOC VARCHAR(5),
    @SOLUONG INT = 1
AS BEGIN TRAN
    DECLARE @ERR VARCHAR(50)
    IF NOT EXISTS (SELECT * FROM GIAYKHAMBENH
        WHERE MAGIAYKHAMBENH = @MAGIAYKHAMBENH) BEGIN
        RAISERROR('INVALID MAGIAYKHAMBENH', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF NOT EXISTS (SELECT * FROM THUOC WHERE MATHUOC = @MATHUOC) BEGIN
        RAISERROR('INVALID MATHUOC', 16, 1)
        ROLLBACK TRAN
        RETURN -2
    END

    IF EXISTS (SELECT * FROM TOATHUOC
        WHERE MAGIAYKHAMBENH = @MAGIAYKHAMBENH AND MATHUOC = @MATHUOC) BEGIN
        RAISERROR('TOATHUOC ALREADY EXISTS', 16, 1)
        ROLLBACK TRAN
        RETURN -3
    END

    DECLARE @COST INT
    SET @COST = (SELECT GIATIEN FROM THUOC
        WHERE MATHUOC = @MATHUOC) * @SOLUONG

    INSERT INTO TOATHUOC
    VALUES (@MAGIAYKHAMBENH, @MATHUOC, @SOLUONG)

    UPDATE GIAYKHAMBENH SET TONGTIENTHUOC += @COST
    WHERE MAGIAYKHAMBENH = @MAGIAYKHAMBENH
COMMIT TRAN
GO

CREATE OR ALTER PROC USP_TOATHUOC_UPD
    @MAGIAYKHAMBENH VARCHAR(5),
    @MATHUOC VARCHAR(5),
    @SOLUONG INT = 1
AS BEGIN TRAN
    DECLARE @ERR VARCHAR(50)
    IF NOT EXISTS (SELECT * FROM GIAYKHAMBENH
        WHERE MAGIAYKHAMBENH = @MAGIAYKHAMBENH) BEGIN
        RAISERROR('INVALID MAGIAYKHAMBENH', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF NOT EXISTS (SELECT * FROM THUOC WHERE MATHUOC = @MATHUOC) BEGIN
        RAISERROR('INVALID MATHUOC', 16, 1)
        ROLLBACK TRAN
        RETURN -2
    END

    IF NOT EXISTS (SELECT * FROM TOATHUOC
        WHERE MAGIAYKHAMBENH = @MAGIAYKHAMBENH AND MATHUOC = @MATHUOC) BEGIN
        RAISERROR('INVALID TOATHUOC', 16, 1)
        ROLLBACK TRAN
        RETURN -3
    END

    DECLARE @OLDCOST INT, @COST INT
    SET @OLDCOST = (SELECT TONGTIENTHUOC FROM GIAYKHAMBENH
        WHERE MAGIAYKHAMBENH = @MAGIAYKHAMBENH)
        - (SELECT GIATIEN FROM THUOC WHERE MATHUOC = @MATHUOC)
        * (SELECT SOLUONG FROM TOATHUOC
        WHERE MAGIAYKHAMBENH = @MAGIAYKHAMBENH AND MATHUOC = @MATHUOC)

    SET @COST = (SELECT GIATIEN FROM THUOC
        WHERE MATHUOC = @MATHUOC) * @SOLUONG

    UPDATE TOATHUOC SET SOLUONG = @SOLUONG
    WHERE MAGIAYKHAMBENH = @MAGIAYKHAMBENH AND MATHUOC = @MATHUOC

    UPDATE GIAYKHAMBENH SET TONGTIENTHUOC = @OLDCOST + @COST
    WHERE MAGIAYKHAMBENH = @MAGIAYKHAMBENH
COMMIT TRAN
GO

CREATE OR ALTER PROC USP_TOATHUOC_DEL
    @MAGIAYKHAMBENH VARCHAR(5),
    @MATHUOC VARCHAR(5)
AS BEGIN TRAN
    DECLARE @ERR VARCHAR(50)
    IF NOT EXISTS (SELECT * FROM GIAYKHAMBENH
        WHERE MAGIAYKHAMBENH = @MAGIAYKHAMBENH) BEGIN
        RAISERROR('INVALID MAGIAYKHAMBENH', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF NOT EXISTS (SELECT * FROM THUOC WHERE MATHUOC = @MATHUOC) BEGIN
        RAISERROR('INVALID MATHUOC', 16, 1)
        ROLLBACK TRAN
        RETURN -2
    END

    IF NOT EXISTS (SELECT * FROM TOATHUOC
        WHERE MAGIAYKHAMBENH = @MAGIAYKHAMBENH AND MATHUOC = @MATHUOC) BEGIN
        RAISERROR('INVALID TOATHUOC', 16, 1)
        ROLLBACK TRAN
        RETURN -3
    END

    DECLARE @COST INT
    SET @COST = (SELECT GIATIEN FROM THUOC WHERE MATHUOC = @MATHUOC)
        * (SELECT SOLUONG FROM TOATHUOC
        WHERE MAGIAYKHAMBENH = @MAGIAYKHAMBENH AND MATHUOC = @MATHUOC)

    DELETE FROM TOATHUOC
    WHERE MAGIAYKHAMBENH = @MAGIAYKHAMBENH AND MATHUOC = @MATHUOC

    UPDATE GIAYKHAMBENH SET TONGTIENTHUOC -= @COST
    WHERE MAGIAYKHAMBENH = @MAGIAYKHAMBENH
COMMIT TRAN
GO

/* Thêm, xóa, sửa DICHVUSUDUNG
 */
CREATE OR ALTER PROC USP_DICHVUSUDUNG_INS
    @MAGIAYKHAMBENH VARCHAR(5),
    @MADICHVU VARCHAR(5),
    @GHICHU VARCHAR(100) = ''
AS BEGIN TRAN
    DECLARE @ERR VARCHAR(50)
    IF NOT EXISTS (SELECT * FROM GIAYKHAMBENH
        WHERE MAGIAYKHAMBENH = @MAGIAYKHAMBENH) BEGIN
        RAISERROR('INVALID MAGIAYKHAMBENH', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF NOT EXISTS (SELECT * FROM DICHVUKHAM WHERE MADICHVU = @MADICHVU) BEGIN
        RAISERROR('INVALID MADICHVU', 16, 1)
        ROLLBACK TRAN
        RETURN -2
    END

    IF EXISTS (SELECT * FROM DICHVUSUDUNG
        WHERE MAGIAYKHAMBENH = @MAGIAYKHAMBENH AND MADICHVU = @MADICHVU) BEGIN
        RAISERROR('DICHVUSUDUNG ALREADY EXISTS', 16, 1)
        ROLLBACK TRAN
        RETURN -3
    END

    DECLARE @COST INT
    SET @COST = (SELECT GIATIEN FROM DICHVUKHAM
        WHERE MADICHVU = @MADICHVU)

    INSERT INTO DICHVUSUDUNG
    VALUES (@MAGIAYKHAMBENH, @MADICHVU, @GHICHU)

    UPDATE GIAYKHAMBENH SET TONGTIENDICHVU += @COST
    WHERE MAGIAYKHAMBENH = @MAGIAYKHAMBENH
COMMIT TRAN
GO

CREATE OR ALTER PROC USP_DICHVUSUDUNG_UPD
    @MAGIAYKHAMBENH VARCHAR(5),
    @MADICHVU VARCHAR(5),
    @GHICHU VARCHAR(100) = ''
AS BEGIN TRAN
    DECLARE @ERR VARCHAR(50)
    IF NOT EXISTS (SELECT * FROM GIAYKHAMBENH
        WHERE MAGIAYKHAMBENH = @MAGIAYKHAMBENH) BEGIN
        RAISERROR('INVALID MAGIAYKHAMBENH', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF NOT EXISTS (SELECT * FROM DICHVUKHAM WHERE MADICHVU = @MADICHVU) BEGIN
        RAISERROR('INVALID MADICHVU', 16, 1)
        ROLLBACK TRAN
        RETURN -2
    END

    IF NOT EXISTS (SELECT * FROM DICHVUSUDUNG
        WHERE MAGIAYKHAMBENH = @MAGIAYKHAMBENH AND MADICHVU = @MADICHVU) BEGIN
        RAISERROR('INVALID DICHVUSUDUNG', 16, 1)
        ROLLBACK TRAN
        RETURN -3
    END

    UPDATE DICHVUSUDUNG SET GHICHU = @GHICHU
    WHERE MAGIAYKHAMBENH = @MAGIAYKHAMBENH AND MADICHVU = @MADICHVU
COMMIT TRAN
GO

CREATE OR ALTER PROC USP_DICHVUSUDUNG_DEL
    @MAGIAYKHAMBENH VARCHAR(5),
    @MADICHVU VARCHAR(5),
    @GHICHU VARCHAR(100) = ''
AS BEGIN TRAN
    DECLARE @ERR VARCHAR(50)
    IF NOT EXISTS (SELECT * FROM GIAYKHAMBENH
        WHERE MAGIAYKHAMBENH = @MAGIAYKHAMBENH) BEGIN
        RAISERROR('INVALID MAGIAYKHAMBENH', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF NOT EXISTS (SELECT * FROM DICHVUKHAM WHERE MADICHVU = @MADICHVU) BEGIN
        RAISERROR('INVALID MADICHVU', 16, 1)
        ROLLBACK TRAN
        RETURN -2
    END

    IF NOT EXISTS (SELECT * FROM DICHVUSUDUNG
        WHERE MAGIAYKHAMBENH = @MAGIAYKHAMBENH AND MADICHVU = @MADICHVU) BEGIN
        RAISERROR('INVALID DICHVUSUDUNG', 16, 1)
        ROLLBACK TRAN
        RETURN -3
    END

    DECLARE @COST INT
    SET @COST = (SELECT GIATIEN FROM DICHVUKHAM
        WHERE MADICHVU = @MADICHVU)

    DELETE FROM DICHVUSUDUNG
    WHERE MAGIAYKHAMBENH = @MAGIAYKHAMBENH AND MADICHVU = @MADICHVU

    UPDATE GIAYKHAMBENH SET TONGTIENDICHVU -= @COST
    WHERE MAGIAYKHAMBENH = @MAGIAYKHAMBENH
COMMIT TRAN
GO