/* 21HTTT1 - Nhóm 3
 * 21127004 - Trần Nguyễn An Phong
 * 21127135 - Diệp Hữu Phúc
 * 21127149 - Huỳnh Minh Quang
 * 21127296 - Đặng Hà Huy
 */
USE [Nhom3_QLNhaKhoa]
GO

--TRAN 1
CREATE OR ALTER PROC USP_THUOC_UPDATE_GIAMGIA
    @NGUOIUPDATE VARCHAR(5),
	@TRYTIME INT = 0
AS SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN

    IF @NGUOIUPDATE NOT LIKE 'AD%' BEGIN
            RAISERROR('ONLY ADMIN MANAGING THIS THUOC CAN UPDATE IT', 16, 1)
            ROLLBACK TRAN
            RETURN -1
        END

 BEGIN TRY 
		UPDATE THUOC
		SET GIATIEN = (GIATIEN *  0.5)
		WHERE DATEDIFF(MONTH, GETDATE(), NGAYHETHAN) <= 6

		WAITFOR DELAY '00:00:05'

		UPDATE THUOC
		SET GIATIEN = (GIATIEN * 0.75)
		WHERE (DATEDIFF(MONTH, GETDATE(), NGAYHETHAN) > 6 AND DATEDIFF(MONTH, GETDATE(), NGAYHETHAN) <= 12)
    END TRY

    BEGIN CATCH
		ROLLBACK TRAN

		WAITFOR DELAY '00:00:03'
		IF (@TRYTIME < 10)
		BEGIN
			DECLARE @NEWTRYTIME INT
			SET @NEWTRYTIME = @TRYTIME + 1

			DECLARE @ERR INT
			EXEC @ERR = USP_THUOC_UPDATE_GIAMGIA @NGUOIUPDATE, @NEWTRYTIME
			RETURN @ERR
		END

		IF (@TRYTIME >= 10)
		BEGIN
			RAISERROR('AN DEADLOCK OCCUR', 16, 1)
			RETURN -2
		END
    END CATCH

COMMIT TRAN
RETURN 0
GO

--TRAN 2
CREATE OR ALTER PROC USP_THUOC_UPDATE_DAYHANG
    @NGUOIUPDATE VARCHAR(5),
	@TRYTIME INT = 0
AS SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
	
    IF @NGUOIUPDATE NOT LIKE 'AD%' BEGIN
		RAISERROR('ONLY ADMIN MANAGING THIS THUOC CAN UPDATE IT', 16, 1)
        ROLLBACK TRAN
        RETURN -1
	END
	
    BEGIN TRY 
		UPDATE THUOC
		SET SOLUONGTONKHO = (SOLUONGTONKHO *  0.5)
		WHERE DATEDIFF(MONTH, GETDATE(), NGAYHETHAN) <= 6

		WAITFOR DELAY '00:00:03'

		UPDATE THUOC
		SET SOLUONGTONKHO = (SOLUONGTONKHO * 0.75)
		WHERE (DATEDIFF(MONTH, GETDATE(), NGAYHETHAN) > 6 AND DATEDIFF(MONTH, GETDATE(), NGAYHETHAN) <= 12)
    END TRY

    BEGIN CATCH
		ROLLBACK TRAN

		WAITFOR DELAY '00:00:05'
		IF (@TRYTIME < 10)
		BEGIN
			DECLARE @NEWTRYTIME INT
			SET @NEWTRYTIME = @TRYTIME + 1
			EXEC USP_THUOC_UPDATE_DAYHANG @NGUOIUPDATE, @NEWTRYTIME
		END

		IF (@TRYTIME >= 10)
		BEGIN
			RAISERROR('AN DEADLOCK OCCUR', 16, 1)
		END
    END CATCH

COMMIT TRAN
RETURN 0
GO