/* 21HTTT1 - Nhóm 3
 * 21127004 - Trần Nguyễn An Phong
 * 21127135 - Diệp Hữu Phúc
 * 21127149 - Huỳnh Minh Quang
 * 21127296 - Đặng Hà Huy
 */
USE [Nhom3_QLNhaKhoa]
GO
--TRAN 1
CREATE OR ALTER PROC USP_THUOC_UPDATE_GIAMGIA
    @NGUOIUPDATE VARCHAR(5)
AS SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN

    IF @NGUOIUPDATE NOT LIKE 'AD%' BEGIN
            RAISERROR('ONLY ADMIN MANAGING THIS THUOC CAN UPDATE IT', 16, 1)
            ROLLBACK TRAN
            RETURN -1
        END


    UPDATE THUOC
    SET GIATIEN = (GIATIEN * 0.75)
    WHERE (DATEDIFF(MONTH, GETDATE(), NGAYHETHAN) > 6 AND DATEDIFF(MONTH, GETDATE(), NGAYHETHAN) <= 12)

    WAITFOR DELAY '00:00:10'


	UPDATE THUOC
    SET GIATIEN = (GIATIEN * 0.4)
    WHERE DATEDIFF(MONTH, GETDATE(), NGAYHETHAN) <= 6

COMMIT TRAN
RETURN 0
GO

--TRAN 2
CREATE OR ALTER PROC USP_THUOC_UPDATE_DAYHANG
    @NGUOIUPDATE VARCHAR(5)
AS SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN

    IF @NGUOIUPDATE NOT LIKE 'AD%' BEGIN
            RAISERROR('ONLY ADMIN MANAGING THIS THUOC CAN UPDATE IT', 16, 1)
            ROLLBACK TRAN
            RETURN -1
        END

    UPDATE THUOC
    SET SOLUONGTONKHO = (SOLUONGTONKHO *  0.5)
    WHERE DATEDIFF(MONTH, GETDATE(), NGAYHETHAN) <= 6

    WAITFOR DELAY '00:00:10'

    UPDATE THUOC
    SET SOLUONGTONKHO = (SOLUONGTONKHO * 0.75)
    WHERE (DATEDIFF(MONTH, GETDATE(), NGAYHETHAN) > 6 AND DATEDIFF(MONTH, GETDATE(), NGAYHETHAN) <= 12)

COMMIT TRAN
RETURN 0
GO