USE [Nhom3_QLNhaKhoa]
GO

EXEC USP_DICHVUKHAM_INS N'KHÁM TỔNG QUÁT', 0
EXEC USP_DICHVUKHAM_INS N'CHỤP X-QUANG', 150
EXEC USP_DICHVUKHAM_INS N'TRÁM RĂNG SỮA', 200
EXEC USP_DICHVUKHAM_INS N'TRÁM CỔ RĂNG', 600
EXEC USP_DICHVUKHAM_INS N'NHỔ RĂNG SỮA', 100
EXEC USP_DICHVUKHAM_INS N'TẨY TRẮNG RĂNG', 3000

EXEC USP_DICHVUKHAM_INS
    N'NIỀNG RĂNG INVISALIGN ĐƠN GIẢN', 34000
EXEC USP_DICHVUKHAM_INS
    N'NIỀNG RĂNG INVISALIGN PHỨC TẠP CẤP I', 67000
EXEC USP_DICHVUKHAM_INS
    N'NIỀNG RĂNG INVISALIGN PHỨC TẠP CẤP II', 90000
EXEC USP_DICHVUKHAM_INS
    N'NIỀNG RĂNG INVISALIGN PHỨC TẠP CẤP III', 121000

GO